In [2]:
# Array Manipulation
# Transpose
import numpy as np
my_array=np.array(np.random.randint(10,30,(2,3)))
print(my_array)

[[10 20 20]
 [25 13 23]]


In [ ]:
my_array.shape

(2, 3)

In [ ]:
my_array2=np.transpose(my_array)
print(my_array2)

[[11 22]
 [15 20]
 [12 25]]


In [ ]:
d3_array=np.array(np.random.randint(5,20,(2,4,6)))
print(d3_array)

[[[ 9  7 11 17 18  7]
  [ 9 16 18 10 18 15]
  [ 8 16  9  7 12 10]
  [11 19  5 19  8  8]]

 [[14 15 16  8 13 19]
  [ 7 13 15  9 14 16]
  [17 18 17 10 10 11]
  [ 8  6 17 17 12 16]]]


In [ ]:
trans=np.transpose(d3_array)
print(trans)

[[[ 9 14]
  [ 9  7]
  [ 8 17]
  [11  8]]

 [[ 7 15]
  [16 13]
  [16 18]
  [19  6]]

 [[11 16]
  [18 15]
  [ 9 17]
  [ 5 17]]

 [[17  8]
  [10  9]
  [ 7 10]
  [19 17]]

 [[18 13]
  [18 14]
  [12 10]
  [ 8 12]]

 [[ 7 19]
  [15 16]
  [10 11]
  [ 8 16]]]


In [ ]:
# Reshape
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr.reshape(2, 3)
print(reshaped_arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
# Resize
arr = np.array(np.random.randint(5,20,(2,3,4)))
print(arr.shape)
resized_arr = np.resize(arr,(3,4,5))
print(resized_arr)
print(resized_arr.shape)

(2, 3, 4)
[[[11 10  6 10 11]
  [13 10 10 11 15]
  [ 8  5 13 10 18]
  [16  7  6 19 10]]

 [[18 17  6  9 11]
  [10  6 10 11 13]
  [10 10 11 15  8]
  [ 5 13 10 18 16]]

 [[ 7  6 19 10 18]
  [17  6  9 11 10]
  [ 6 10 11 13 10]
  [10 11 15  8  5]]]
(3, 4, 5)


In [ ]:
arr1 = np.array(np.random.randint(5,20,(2,3,4)))
print(arr1.shape)
print(arr1)
print(arr1.flatten())

(2, 3, 4)
[[[17 14 10 12]
  [16 11 12 14]
  [11 17  5 19]]

 [[13 12 13  9]
  [ 9  8 14  6]
  [ 7 10  9 10]]]
[17 14 10 12 16 11 12 14 11 17  5 19 13 12 13  9  9  8 14  6  7 10  9 10]


In [ ]:
# Insert
arr1 = np.array(np.random.randint(5,20,(2,3,4)))
print(arr1)
print(arr1.shape)
np.insert(arr1,2,50,axis=1)

[[[12  7 11 18]
  [10 12 19 16]
  [14 13 12  6]]

 [[15  6 18 10]
  [11  6 14 14]
  [ 8 17 13  5]]]
(2, 3, 4)


array([[[12,  7, 11, 18],
        [10, 12, 19, 16],
        [50, 50, 50, 50],
        [14, 13, 12,  6]],

       [[15,  6, 18, 10],
        [11,  6, 14, 14],
        [50, 50, 50, 50],
        [ 8, 17, 13,  5]]])

In [ ]:
# Append
arr2 = np.array(np.random.randint(10,20,(2,3,4)))
print(arr2)
print(arr2.shape)
np.append(arr2,20)

[[[13 17 12 14]
  [11 13 14 19]
  [12 14 17 12]]

 [[11 10 18 15]
  [10 12 10 13]
  [14 16 16 12]]]
(2, 3, 4)


array([13, 17, 12, 14, 11, 13, 14, 19, 12, 14, 17, 12, 11, 10, 18, 15, 10,
       12, 10, 13, 14, 16, 16, 12, 20])

In [ ]:
# Delete
arr2 = np.array(np.random.randint(10,20,(2,3,4)))
print(arr2)
print(arr2.shape)
np.delete(arr2,(1,2),axis=1)

[[[13 12 14 15]
  [19 18 18 13]
  [14 15 14 14]]

 [[17 12 16 11]
  [15 13 15 14]
  [18 14 17 15]]]
(2, 3, 4)


array([[[13, 12, 14, 15]],

       [[17, 12, 16, 11]]])

In [ ]:
# Unique
arr3 = np.array(np.random.randint(10,30,(2,3,4)))
print(arr3)
print(arr3.shape)
np.unique(arr3,return_counts=True,return_index=True)

[[[22 12 27 27]
  [12 24 10 23]
  [26 21 24 17]]

 [[23 16 13 29]
  [22 11 11 29]
  [26 16 23 25]]]
(2, 3, 4)


(array([10, 11, 12, 13, 16, 17, 21, 22, 23, 24, 25, 26, 27, 29]),
 array([ 6, 17,  1, 14, 13, 11,  9,  0,  7,  5, 23,  8,  2, 15]),
 array([1, 2, 2, 1, 2, 1, 1, 2, 3, 2, 1, 2, 2, 2]))

In [ ]:
# Copy and View
# List
a=[2,4,6]
b=a
b[0]=5
print(b)
print(a)

[5, 4, 6]
[5, 4, 6]


In [ ]:
# Using copy method
a=[2,4,6]
b=a.copy()
b[0]=5
print(b)
print(a)

[5, 4, 6]
[2, 4, 6]


In [ ]:
# Array
a=np.array([3,5,7])
b=a
b[0]=223
print(b)
print(a)

[223   5   7]
[223   5   7]


In [ ]:
a=np.array([3,5,7])
b=a.copy()
b[0]=223
print(b)
print(a)

[223   5   7]
[3 5 7]


In [3]:
# Broadcasting
np.arange(5)+3

array([3, 4, 5, 6, 7])

In [4]:
np.ones((2,4))+np.arange(4)

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [6]:
np.arange(8).reshape(2,4)+np.arange(4)

array([[ 0,  2,  4,  6],
       [ 4,  6,  8, 10]])

In [8]:
# Multiply
arr=np.random.randint(2,10,(1,3))
print(arr)
arr1=np.random.randint(1,5,(3,1))
print(arr1)

[[7 5 2]]
[[3]
 [1]
 [2]]


In [9]:
np.multiply(arr,arr1)

array([[21, 15,  6],
       [ 7,  5,  2],
       [14, 10,  4]])

In [10]:
# Divide
np.divide(arr,arr1)

array([[2.33333333, 1.66666667, 0.66666667],
       [7.        , 5.        , 2.        ],
       [3.5       , 2.5       , 1.        ]])

In [11]:
# Aggregation operations
a=np.random.randint(2,20,(2,5))
print(a)

[[12 12 13  4  7]
 [ 3  5 15 11 17]]


In [12]:
print(np.sum(a))
print(np.sum(a,axis=0))
print(np.sum(a,axis=1))

99
[15 17 28 15 24]
[48 51]


In [13]:
print(np.min(a))
print(np.min(a,axis=1))

3
[4 3]


In [14]:
print(np.sort(a))

[[ 4  7 12 12 13]
 [ 3  5 11 15 17]]
